### ISSUE TITLE
External search shows no Hollo account details

### ISSUE THREAD

**Issue by okpierre** [dahlia/hollo#1]
Use the search bar within pixelfed I use the format @username@domain for both

What am I doing wrong?

pixelfed -> mastodon account
```
status 200
search?q=@test@mastodon.test&resolve=true&_pe=1
```

json response
**accounts: [ {...} ]**
hashtags: [ ]
statuses: [ ]

pixelfed -> hollo account
```
status 200
search?q=@test@hollo.test&resolve=true&_pe=1
```

json response
accounts: [ ]
hashtags: [ ]
statuses: [ ]

**Comment by dahlia** [comment]
Hmm… I can't reproduce this.  Could you let me know the instructions to reproduce it?

**Comment by okpierre** [comment]
> Hmm… I can't reproduce this. Could you let me know the instructions to reproduce it?

I used the Pixelfed search bar and typed in the new Hollo test account that I created. Very high chance it is user error on my part. Thanks for looking into it

**Comment by okpierre** [comment]
Hi @dahlia I had time to do another test

Once again I'm using the search bar within Pixelfed

Working: search for mastodon user (shows popup to click)
![pixelfedsearchmatodon](https://github.com/user-attachments/assets/88a467df-7e60-4ad4-bc46-cd95b5ce1732)

Not working: search for johndoe (no popup to click)
![pixelfedsearchhollo](https://github.com/user-attachments/assets/59d07a7f-2aa6-426a-93f8-d2f078db1fc9)

Log when searching this format `@johndoe@030af5663d0892762c6eef6f793940c1.serveo.net`

```
INF fedify·federation·http GET /.well-known/webfinger?resource=acct:johndoe@030af5663d0892762c6eef6f793940c1.serveo.net: 200
```

Log when searching this format `https://030af5663d0892762c6eef6f793940c1.serveo.net/@johndoe`

`INF fedify·federation·http GET /@johndoe: 200`


Could the long subdomain cause this issue? Am I missing a configuration?

**Comment by dahlia** [comment]
To determine the cause of this issue, we'll need to check Pixelfed's server-side logs. I think I need to spin up a Pixelfed instance for reproducing and testing.
