### ISSUE TITLE
Support using file systems instead of S3

### ISSUE THREAD

**Issue by XiNiHa** [dahlia/hollo#10]
Currently, running Hollo requires using an S3-compatible storage solution. However, serving files from the filesystem is both easy for simple use cases and scalable for larger deployments (considering the usage of something like [Kubernetes CSI](https://kubernetes-csi.github.io/docs/drivers.html)), so it would be great to support those use cases.

**Comment by XiNiHa** [comment]
Actually I thought about using [`unstorage`](https://github.com/unjs/unstorage/) and found that it doesn't have S3 adapter which is very surprising 🤯

**Comment by ThisIsMissEm** [comment]
Unstorage possibly isn't what you want, but flydrive is made by the Adonis team and afaik should support most target environments that Hollo supports

**Comment by ThisIsMissEm** [comment]
Looking further into FlyDrive, it should be possible to use with Bun, as it looks like it supports all the node:fs APIs required. And if we want we could write a custom driver extending the FsDriver to use the Bun File APIs
