### ISSUE TITLE
Mute

### ISSUE THREAD

**Issue by dahlia** [dahlia/hollo#15]
Implement a mute feature to ignore specific accounts or domains.

See also:

- [x] [`GET /api/v1/mutes`](https://docs.joinmastodon.org/methods/mutes/#get)
- [x] [`POST /api/v1/accounts/:id/mute`](https://docs.joinmastodon.org/methods/accounts/#mute)
- [x] [`POST /api/v1/accounts/:id/unmute`](https://docs.joinmastodon.org/methods/accounts/#unmute)

**Comment by devtedlee** [comment]
이슈 해결 시도해보겠습니다.
