### ISSUE TITLE
contact and registrations in v2/instance should be at top level

### ISSUE THREAD

**Issue by technicat** [dahlia/hollo#2]
Hello, currently the contact and registrations fields in v2/instance are returned within the configuration data but they should be at the top level of the returned data.

https://docs.joinmastodon.org/entities/Instance/

**Comment by dahlia** [comment]
Fixed now! E.g., <https://hollo.social/api/v2/instance>.

**Comment by technicat** [comment]
![image](https://github.com/user-attachments/assets/9ed75ae6-7aab-4706-bf12-eaf32912112a)

**Comment by dahlia** [comment]
@technicat Great!
