### ISSUE TITLE
How do you authorize applications to request token?

### ISSUE THREAD

**Issue by dmitrizagidulin** [dahlia/hollo#29]
Hi, I'm trying to test out Hollo. I created a login and an account. 
But not sure what to do afterwards. The instructions say to use a client (like Phanpy). 
I went to Phanpy login, selected the URL for the installation, and it started the OAuth authorization procedure (redirected to `/oauth/authorize?client_id=V6wKmBaF1h-f0fSsMAIf_eiulFeTOqtyN2cUVvc7NVg&scope=read+write+follow+push&redirect_uri=https%3A%2F%2Fphanpy.social%2F&response_type=code`  - so far so good, as expected.

And then Hollo gave me a `invalid_client_id` error -- which makes sense, since that client was not registered in the database.
How do I register an application in the database, so I can get a token for it etc?

**Comment by dahlia** [comment]
You don't have to manually register an application in the database. It should be done automatically. Have you tried in localhost?

**Comment by dmitrizagidulin** [comment]
Ok, installed `ngrok` on your advice, gotten as far as the authorization screen:

![image](https://github.com/user-attachments/assets/9f047d73-86b7-4b8d-93de-1b446121c1e6)

As soon as I hit 'Authorize' though, it redirects back to Phanpy (correctly) with the OAuth2 code, but then:

![image](https://github.com/user-attachments/assets/70e2262e-b04c-48a7-b176-4035a566d48d)

and the browser console just has 401 errors:
![image](https://github.com/user-attachments/assets/b6ef049d-5e31-4f48-98d1-eab4cc14dd17)

And Phanpy doesn't seem logged in (the menu has Log In option again).

Seemingly no errors in the Hollo server console:
```
23:39:40.424 INF fedify·federation·http GET /oauth/authorize?client_id=O_spsK8WHSJy7Wh2SZgaiw&code_challenge_method=S256&code_challenge=LNKbKTHtXyik4ZE2lWUkdkIydRXObtfw2Rjt90woPFY&redirect_uri=https%3A%2F%2Fphanpy.social%2F&response_type=code&scope=read+write+follow+push: 200
23:39:40.754 INF fedify·federation·http GET /favicon.ico: 200
23:42:15.540 INF fedify·federation·http POST /oauth/authorize: 302
23:42:16.468 INF fedify·federation·http POST /oauth/token: 200
23:42:16.567 INF fedify·federation·http OPTIONS /api/v2/instance: 204
23:42:16.568 INF fedify·federation·http OPTIONS /api/v1/preferences: 204
23:42:16.568 INF fedify·federation·http OPTIONS /api/v1/instance: 204
23:42:16.568 INF fedify·federation·http OPTIONS /api/v1/accounts/verify_credentials: 204

```

Am I missing something obvious?

**Comment by dmitrizagidulin** [comment]
Er, I have _no_ idea why Phanpy is requesting `mastodon.social/api/v1/timelines/home`, there.

**Comment by dahlia** [comment]
> Er, I have _no_ idea why Phanpy is requesting `mastodon.social/api/v1/timelines/home`, there.

That's really strange. 🤔 Could you give [Elk](https://elk.zone/) a try?

**Comment by dmitrizagidulin** [comment]
@dahlia ok, tried Elk. Signed in, got to the Authorization page, clicked Allow, got this error:

`ERROR: to: The server returned data with an unknown encoding.`

This was the server-side Hollo console:

```
22:38:03.953 INF fedify·federation·http GET /oauth/authorize?client_id=GfNzVt2ySRlquJy-UUI1Ww&force_login=false&scope=read+write+follow+push&response_type=code&lang=en-US&redirect_uri=https:%2F%2Felk.zone%2Fapi%2Frightly-active-bear.ngrok-free.app%2Foauth%2Fhttps%253A%252F%252Felk.zone: 200
22:38:04.564 INF fedify·federation·http GET /favicon.ico: 200
22:38:08.140 INF fedify·federation·http POST /oauth/authorize: 302
22:38:08.427 INF fedify·federation·http POST /oauth/token: 200
22:38:09.262 INF fedify·federation·http OPTIONS /api/v1/instance: 204
22:38:09.263 INF fedify·federation·http OPTIONS /api/v1/preferences: 204
22:38:09.264 INF fedify·federation·http OPTIONS /api/v1/push/subscription: 204
22:38:09.266 INF fedify·federation·http OPTIONS /api/v1/accounts/verify_credentials: 204
22:38:09.269 INF fedify·federation·http OPTIONS /api/v1/timelines/home?limit=30: 204
22:38:09.617 INF fedify·federation·http OPTIONS /api/v1/timelines/public?limit=30&local=true: 204
```

Which looks mostly normal, although I'm curious why there's no GET calls from Elk after the `POST /oauth/token: 200` request.

Looking at the Elk browser console (and going debugging the "unknown encoding" error), it looks like it's erroring on the OPTIONS calls, specifically `return await e.v1.preferences.fetch()` (that's on the Elk side).

Any advice on what other clients I can try? Which ones do you use?

**Comment by dmitrizagidulin** [comment]
Ok I think I know at least why the `/api/v1/preferences` is failing with the unknown encoding error. It's the Ngrok "you're about to visit this free page" warning that's doing it.

**Comment by dmitrizagidulin** [comment]
@dahlia ok, I was able to make a post via Phanpy and Elk now (after fixing the 'free ngrok page' error).
Thanks again for your help! Closing the issue.
