### ISSUE TITLE
Unable to access some ActivityPub accounts

### ISSUE THREAD

**Issue by ntsklab** [dahlia/hollo#35]
**Occurring problem**

```
@029bot@mi.signboard.fun
@kirikanbot@mi.signboard.fun
```

The above account does not appear in the search and I cannot follow it.

Also, accounts via fed.brid.gy do not appear in the search and cannot be followed.
For example, `@bsky.brid.gy@bsky.brid.gy` and `@ntsk.oyasumi.dev@bsky.brid.gy` are accounts via bridges.

**Screenshot of the problem**
https://hl.oyasumi.dev/@ntek/0192996c-4a44-7430-bf73-c97c299953c1

**Tried Mastodon clients**
Elk
Phanpy
Moshidon

**Expected behavior**
The above accounts should appear in searches and be able to be followed.

Translated by DeepL.

**Comment by dahlia** [comment]
This bug was caused by a bug in Nexkey, which we fixed to work around the corresponding bug in Nexkey at the Fedify level. It should work fine with the current version of Hollo.

このバグはNexkeyのバグによるもので、FedifyレベルでNexkeyの該当バグを回避する様に修正して解決しました。現在Holloの最新バージョンでは上手く動作するはずです。
