### ISSUE TITLE
Unable to log in from SubwayTooter app.

### ISSUE THREAD

**Issue by ntsklab** [dahlia/hollo#37]
**Problem Details**
Tried to test emoji reactions from other apps, but could not log in from SubwayTooter.

**Screenshot of the problem**
https://hl.oyasumi.dev/@ntek/01929f8f-0768-7988-9b82-f31819f7deb8

Please let us know if you need any other information.

**Comment by dahlia** [comment]
You can now sign in with Hollo on Subway Tooter.

Subway TooterでHolloでログイン出来る様に成りました。
