### ISSUE TITLE
Show the number of likes and shares in a post view

### ISSUE THREAD

**Issue by dahlia** [dahlia/hollo#4]
![Hollo's current post view](https://github.com/user-attachments/assets/12c303c2-f0af-42d3-af1b-3c27f6355055)

Hollo's current post view does not have the number of likes or the number of shares.  It would be good if it has those numbers as like Mastodon, etc. do.  The best place would be next to the timestamp.

**Comment by devtedlee** [comment]
제가 진행 하겠습니다.
