### ISSUE TITLE
Pagination on the profile page

### ISSUE THREAD

**Issue by dahlia** [dahlia/hollo#40]
Currently the profile page lists all posts without any pagination. This is fine when there aren't many posts, but it becomes increasingly problematic as more posts are made.

**Comment by maybeanerd** [comment]
I think this might also cause the following issue I observed when using moshidon:

https://github.com/user-attachments/assets/2fd88176-c5bf-42c9-b600-2e53771d94ad

**Comment by dahlia** [comment]
> I think this might also be related to the following issue I observed when using moshidon?@

@maybeanerd That looks like a separate issue.  Could you open a new issue for it?

**Comment by maybeanerd** [comment]
Sure! https://github.com/dahlia/hollo/issues/48
