### ISSUE TITLE
how to configure nginx

### ISSUE THREAD

**Issue by anno189** [dahlia/hollo#51]
I encountered the following issue while configuring nginx. 
1. Cross domain issues.
2. Images cannot be uploaded. 

Can you provide a correct configuration template.

**Comment by dahlia** [comment]
Could you give us more details (like what error messages are shown)?

**Comment by ThisIsMissEm** [comment]
@dahlia I think this might be the BEHIND_PROXY setting at play? In a lot of other software they have an environment variable that says "this is the canonical domain I'm located at and these are the domain(s) that also work"

I could probably spin up a digitalocean box today and do some testing to create an nginx config based off the one we have for Mastodon.

**Comment by dahlia** [comment]
Fedify currently determines its hostname by looking at the `Host` header of each request, which make it non-straightforward behind a reverse proxy… (You know, [x-forwarded-fetch] is exactly for that situation.)

We might need to add an explicit host configuration to Fedify. 🤔 

[x-forwarded-fetch]: https://github.com/dahlia/x-forwarded-fetch
