### ISSUE TITLE
Container for tag 0.1.3 is missing

### ISSUE THREAD

**Issue by HelgeKrueger** [dahlia/hollo#52]
I get, when I try to pull it.

ERROR: failed to solve: ghcr.io/dahlia/hollo:0.1.3: failed to resolve source metadata for ghcr.io/dahlia/hollo:0.1.3: ghcr.io/dahlia/hollo:0.1.3: not found

Would it be possible to build it?

Once I have that (and a few other things, PR incoming), I can add hollo to https://data.funfedi.dev/

**Comment by dahlia** [comment]
Pushed! https://github.com/dahlia/hollo/pkgs/container/hollo/295861446?tag=0.1.3
