### ISSUE TITLE
picture upload error

### ISSUE THREAD

**Issue by anno189** [dahlia/hollo#54]
client: phanpy

client error:

<img width="644" alt="截屏2024-10-29 13 00 28" src="https://github.com/user-attachments/assets/790cca8e-36e1-4649-8c46-08d9c43efb76">

chrome error:

<img width="435" alt="截屏2024-10-29 12 54 30" src="https://github.com/user-attachments/assets/dad814aa-b664-44df-8108-a7dc3c95df87">

**Comment by dahlia** [comment]
Are there any relevant logs in the server log?

**Comment by anno189** [comment]
24 | });
25 | module.exports = __toCommonJS(src_exports);
26 | var import_querystring_parser = require("@smithy/querystring-parser");
27 | var parseUrl = /* @__PURE__ */ __name((url) => {
28 |   if (typeof url === "string") {
29 |     return parseUrl(new URL(url));
                         ^
TypeError: "" cannot be parsed as a URL.
 code: "ERR_INVALID_URL"

      at parseUrl (/root/hollo/node_modules/@smithy/url-parser/dist-cjs/index.js:29:21)
      at toEndpointV1 (/root/hollo/node_modules/@smithy/middleware-endpoint/dist-cjs/index.js:112:32)
      at /root/hollo/node_modules/@smithy/middleware-endpoint/dist-cjs/index.js:232:65

09:18:28.811 ERR fedify·federation·http: 'POST' '/api/v2/media': 500

**Comment by dahlia** [comment]
What kind of object storage do you use?

**Comment by anno189** [comment]
I installed the program on the Aliyun server and used nginx as a forwarding agent.

**Comment by dahlia** [comment]
So… do you use 阿里云对象存储 OSS (Object Storage Service) then?

**Comment by anno189** [comment]
No storage objects were used. 
Or does this program require the use of a storage object? If that's the case, then I understand. 
You can close this issue now.

**Comment by anno189** [comment]
I noticed this text:

>To deploy Hollo, you need S3 or S3-compatible object storage for storing media such as images. There are many S3-compatible object storage services, including AWS S3, Cloudflare R2, MinIO, DigitalOcean Spaces, and Linode Object Storage. Once you have your object storage ready, you’ll need to configure the environment variables

thanks.
