### ISSUE TITLE
Etymology Hollo

### ISSUE THREAD

**Issue by nhrones** [dahlia/hollo#55]
Etymology HoLlo -- which means alone or solitary.  --> But federated

This reminds me of the concept of a **Holon** :
```
Holons: The individual parts of a holarchy that are simultaneously both 
parts of a larger system and individual "wholes". 

Holarchy: A type of organizational structure where decision-making 
and leadership responsibilities are shared among all holons.
```

**Comment by ThisIsMissEm** [comment]
The project name is "Hollo" not "Holo"...?

**Comment by nhrones** [comment]
> The project name is "Hollo" not "Holo"...?

Good catch.  I've corrected.

**Comment by dahlia** [comment]
So… what is this suggesting?

**Comment by ThisIsMissEm** [comment]
@dahlia I don't think anything?

**Comment by nhrones** [comment]
I was just making an observation.  Nothing intended at all.
