### ISSUE TITLE
Threads-style quotes

### ISSUE THREAD

**Issue by dahlia** [dahlia/hollo#6]
According to an [article] of the *Engineering at Meta* blog:

> There are a handful of unofficial methods for handling quote posts in ActivityPub. One fediverse enhancement proposal (FEP), [FEP-e232](https://codeberg.org/fediverse/fep/src/branch/main/fep/e232/fep-e232.md), proposes a way to represent inline quotes and other text-based links to ActivityPub in a manner similar to mentions on other social media platforms. Another method would be to use the `quoteURL` property within ActivityPub, which would assign posts an ID that could then be pulled into other posts that want to quote them. [Misskey created its own solution](https://misskey-hub.net/ns/) with its `_misskey_quote` property, which builds on FEP-e232.
> 
> Many fediverse servers also append extra syntax (`RE:<quoted post URL>`) to post content to make it compatible with servers that haven’t implemented any of the structured methods for handling quote posts.
> 
> After exploring different options pursued by the fediverse community, we chose to implement both FEP-e232 and `_misskey_quote` to federate quote posts on Threads. As of now, none of these methods are official keys in the ActivityPub namespace. We chose `_misskey_quote` because its naming makes it clear that it’s not an official ActivityPub method, and because we know that it’s supported by Misskey, Firefish, and potentially other servers that use quote posts.
> 
> In our current implementation, if a Threads user creates a quote post from a federated post, the quote post will contain a permalink URL (e.g. “`RE: <URL to permalink>`”) to the post along with a structured representation of the post. Platforms outside of Threads can display the quote post similar to how it’s displayed on Threads by using the structured representation to fetch the post and display it within the quote post.
> 
> If the post being quoted is not federated, the quote post’s content will only contain the permalink URL and not the structured representation.

[article]: https://engineering.fb.com/2024/03/21/networking-traffic/threads-has-entered-the-fediverse/

**Comment by longfin** [comment]
@dahlia Could I dig it?

**Comment by dahlia** [comment]
Great, go for it!

**Comment by dahlia** [comment]
I'm working on it.

**Comment by dahlia** [comment]
Fedify added the `Note.quoteUrl` property: <https://github.com/dahlia/fedify/commit/22e07c3fc7a13cc43a1c0b889773db7334b4820f>.
