### ISSUE TITLE
Replies without Mention are not shown in Notification.

### ISSUE THREAD

**Issue by ntsklab** [dahlia/hollo#62]
Version : Hollo 0.2.1

Steps to Reproduce
- Post something on your Hollo account.
- Reply to the post without @<user id> mention

Expected behavior
Like Mastodon, replies without an atmark are also displayed in the notification field.

**Comment by dahlia** [comment]
Fixed in [0.2.2](https://github.com/dahlia/hollo/pkgs/container/hollo/301929452?tag=0.2.2).
