### ISSUE TITLE
`/.well-known/nodeinfo` should have `Content-Type: application/json`

### ISSUE THREAD

**Issue by Steffo99** [dahlia/hollo#66]
NodeInfo uses the same JRD format as `/.well-known/host-meta`, which is described in [RFC 6415](https://datatracker.ietf.org/doc/html/rfc6415#appendix-A):

> The client MAY request a JRD representation using the HTTP "Accept" request header field with a value of "application/json".  
> The server MUST include the HTTP "Content-Type" response header field with a value of "application/json".  
> Any other "Content-Type" value (or lack thereof) indicates that the server does not support the JRD format.

Currently, Hollo (and a couple other fediverse backends!) return a `Content-Type` of `application/jrd+json` instead, which, despite being similar to the `application/xrd+xml` used by the XML-based XRD format, isn't conformant to the specification.

**Comment by ThisIsMissEm** [comment]
`application/json` and `application/jrd+json` are interchangeable here: they are both JSON content types, one just specifically says it's jrd format the other doesn't.

**Comment by ThisIsMissEm** [comment]
Also, the Webfinger proposed standard introduces `application/jrd+json`: https://www.rfc-editor.org/rfc/rfc7033.html#section-10.2

**Comment by Steffo99** [comment]
Oh, I missed that!

Perfect! Nevermind :)
