### ISSUE TITLE
Image rotation metadata is not applied correctly to generated preview images

### ISSUE THREAD

**Issue by aliceif** [dahlia/hollo#76]
When an image from an external post has rotation metadata it seems to get its preview generated with the wrong orientation.
An example I have seen would be this post, where the mouse should be facing to the left: https://labyrinth.zone/notice/Al7CfjGwR17QRQpFTM

**Comment by dahlia** [comment]
It will be fixed in Hollo 0.3.2.

**Comment by dahlia** [comment]
Fixed in [Hollo 0.3.2](https://github.com/dahlia/hollo/pkgs/container/hollo/324829095?tag=0.3.2).

**Comment by aliceif** [comment]
It seems that now for some images the thumbnail is of a inverted aspect ratio compared to the incoming image:
A 260x58 image like
https://drive.nya.social/files2410/69575971-9e1e-42a8-98ab-a3ba141f19af.webp
gets thumbnailed to be 58x260
https://minio-hollo.x27.one/hollo-live/media/0193de22-0a90-7030-a485-dd8a1d013449/thumbnail.webp

**Comment by dahlia** [comment]
Fixed in [Hollo 0.3.3](https://github.com/dahlia/hollo/pkgs/container/hollo/325738254?tag=0.3.3).
