### ISSUE TITLE
Configure Timezone?

### ISSUE THREAD

**Issue by reggi** [dahlia/hollo#82]
Im seeing [12/27/2024, 5:06:31 PM](https://social.reggi.com/@reggi/01940915-7de4-7fdd-a7a3-6695abcf66bd) but its 12:06pm

Is there a way to configure the timezone? 

I've seen the internet advise against setting the server timezone. I'm using railway.

**Comment by ThisIsMissEm** [comment]
You could use the `TZ` environment variable if using node.js for hollo, however, really you do want this to be UTC not a local timezone. Timezone conversion should be done by clients.

**Comment by ThisIsMissEm** [comment]
These links may help:
- https://www.w3.org/TR/timezone/
- https://phrase.com/blog/posts/date-time-localization/
- https://www.nikgraf.com/blog/managing-timezones-in-javascript-apps

**Comment by reggi** [comment]
good point @ThisIsMissEm the default config uses bun https://bun.sh/guides/runtime/timezone which also uses TZ. 

would be good to document that to set the timezone for hollo (as a client) use the TZ env var.

confirmed it worked here!

![Image](https://github.com/user-attachments/assets/8dbbb1e6-8ada-457d-8e06-86f96db0910e)

**Comment by reggi** [comment]
@dahlia feel free to close this one

**Comment by dahlia** [comment]
I'll close this after documenting the `TZ` environment variable!

**Comment by dahlia** [comment]
Now it's documented: <https://docs.hollo.social/install/env/#tz>.
